colorScheme = "congo"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
enableMathNotation = true
defaultBackgroundImage = "img/background.svg"
defaultFeaturedImage = "img/featured.jpg"
[homepage]
  layout = "hero"
  showRecent = true
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = "/posts/"
  cardView = false
  homepageImage = "img/background.jpg"
  disableHeroImageFilter = false

[header]
  layout = "basic"

[footer]
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[article]
  showDate = true
  showViews = false
  showLikes = false
  showAuthor = true
  showAuthorBottom = true
  showHero = true
  heroStyle = "background"
  showTableOfContents = false
  showComments = true
  showSummary = true
  showEdit = false
  showTaxonomies = true
  showWordCount = false
  sharingLinks = []

[list]
  groupByYear = true
  cardView = true
  showTaxonomies = true
  showSummary = true
  showWordCount = false

[sitemap]
  excludedKinds = []
